/*
  Nathan Nguyen
  CSC 355 Section 510
  Assignment 4
  February 3rd, 2021
*/

-- 1
SELECT TNAME, AID, ANAME
	FROM TEAM, AGENT, ASSIGNMENT
	WHERE TEAM.TNAME = 'Ghost' AND TEAM.TID = ASSIGNMENT.TEAMID AND ASSIGNMENT.AGENTID = AGENT.AID
	ORDER BY AID;
	
-- 2
SELECT TNAME
	FROM TEAM, AGENT
	WHERE AGENT.ANAME = 'Jim Phelps' AND TEAM.LEADERID = AGENT.AID
	ORDER BY TNAME;
	
-- 3
SELECT AGENTID, ANAME, COUNT(DISTINCT TEAMID) AS "TEAMS JOINED"
	FROM AGENT INNER JOIN ASSIGNMENT
		ON AGENTID = AID
	GROUP BY AGENTID, ANAME
	ORDER BY COUNT(DISTINCT TEAMID) DESC;
	
-- 4
SELECT DISTINCT LOCATION
	FROM MISSION INNER JOIN ASSIGNMENT
		ON MISSION.TEAMID = ASSIGNMENT.TEAMID
			INNER JOIN TEAM
				ON ASSIGNMENT.TEAMID = TEAM.TID
	WHERE TNAME = 'Fallout';

-- 5
SELECT TID, TNAME, SUM(HOURS)
	FROM TEAM FULL OUTER JOIN ASSIGNMENT
		ON TEAM.TID = ASSIGNMENT.TEAMID
	GROUP BY TID, TNAME
	ORDER BY SUM(HOURS) DESC;
	
-- 6
SELECT DISTINCT MISSIONID, ANAME
	FROM MISSION INNER JOIN TEAM
		ON MISSION.TEAMID = TEAM.TID
			INNER JOIN AGENT
				ON TEAM.LEADERID = AGENT.AID;

-- 7
SELECT ANAME, SALARY
	FROM AGENT 
	WHERE AID NOT IN (SELECT LEADERID
				FROM TEAM
				GROUP BY LEADERID)
	ORDER BY SALARY;
	
-- 8
SELECT COUNT(MISSIONID) AS "MISSIONS PERFORMED WITH WILLIAM BRANDT"
	FROM MISSION INNER JOIN ASSIGNMENT
		ON MISSION.TEAMID = ASSIGNMENT.TEAMID
			INNER JOIN TEAM
				ON MISSION.TEAMID = TID
					INNER JOIN AGENT
						ON AGENTID = AID
	WHERE ANAME = 'William Brandt';