DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
CREATE TABLE EMPLOYEE
(
	ID		CHAR(4)		PRIMARY KEY,
	Name		VARCHAR2(12),
	Dept		CHAR(3),
	Type		NUMBER(1,0),
	Hours		NUMBER(3,0)
);
INSERT INTO EMPLOYEE VALUES ('9009', 'Roger', 'Pub', 2, 20);
INSERT INTO EMPLOYEE VALUES ('3322', 'Pete', 'Eng', 3, 30);
INSERT INTO EMPLOYEE VALUES ('4115', 'John', 'Eng', 1, 30);
INSERT INTO EMPLOYEE VALUES ('3099', 'Keith', 'Hum', 2, 10);
INSERT INTO EMPLOYEE VALUES ('4724', 'Kenny', 'Pub', 1, 15);
SELECT * FROM EMPLOYEE;
DROP TABLE WAGES;
CREATE TABLE WAGES
(
	Wage1		NUMBER(4,2),
	Wage2		NUMBER(4,2),
	Wage3		NUMBER(4,2)
);
INSERT INTO WAGES VALUES (20.00, 40.00, 55.00);
SELECT * FROM WAGES;
COMMIT;